Rightpoint.UnitTesting.Demo.Mvc/Models/PrimaryObject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Rightpoint.UnitTesting.Demo.Mvc.Models
{
    public class PrimaryObject
    {
        public Guid? Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        public IEnumerable<SecondaryObject> SecondaryObjects { get; set; }
    }
}

Rightpoint.UnitTesting.Demo.Mvc/Controllers/PrimaryObjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using EnsureThat;
using Rightpoint.UnitTesting.Demo.Mvc.Contracts;

namespace Rightpoint.UnitTesting.Demo.Mvc.Controllers
{
    [RoutePrefix("primaryobjects")]
    public class PrimaryObjectsController : BaseController
    {
        private readonly IPrimaryObjectService _primaryObjectService;
        private readonly ISecondaryObjectService _secondaryObjectService;

        public PrimaryObjectsController(
            IPrimaryObjectService primaryObjectService,
            ISecondaryObjectService secondaryObjectService)
        {
            Ensure.That(primaryObjectService, nameof(primaryObjectService)).IsNotNull();
            Ensure.That(secondaryObjectService, nameof(secondaryObjectService)).IsNotNull();

            this._primaryObjectService = primaryObjectService;
            this._secondaryObjectService = secondaryObjectService;
        }

        // GET: PrimaryObjects
        [HttpGet]
        [Route("")]
        public async Task<ActionResult> Index()
        {
            var primaryObjects = await _primaryObjectService.GetAllAsync();
            var models = primaryObjects.Select(po => new Models.PrimaryObject()
            {
                Id = po.Id,
                Description = po.Description,
                Name = po.Name,
                SecondaryObjects = new Models.SecondaryObject[0],
            })
            .OrderBy(_ => _.Name)
            .ToArray();

            return View(models);
        }

        // GET: PrimaryObjects/Create
        [HttpGet]
        [Route("create")]
        public ActionResult Create()
        {
            var model = new Models.PrimaryObject();
            return View(model);
        }

        // POST: PrimaryObjects/Create
        [HttpPost]
        [Route("create")]
        public async Task<ActionResult> Create(FormCollection collection)
        {
            var model = new Models.PrimaryObject()
            {
                Description = collection[nameof(Models.PrimaryObject.Description)],
                Name = collection[nameof(Models.PrimaryObject.Name)],
                SecondaryObjects = new Models.SecondaryObject[0],
            };

            try
            {
                await _primaryObjectService.CreateAsync(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        // GET: PrimaryObjects/Edit/5
        [HttpGet]
        [Route("edit")]
        public async Task<ActionResult> Edit(Guid id)
        {
            var primaryObject = await _primaryObjectService.GetAsync(id);
            var secondaryObjectModels = new List<Models.SecondaryObject>();

            if (primaryObject.SecondaryObjects != null)
            {
                foreach (var secondaryObjectThin in primaryObject.SecondaryObjects.Where(so => so.Id.HasValue))
                {
                    var secondaryObject = await _secondaryObjectService.GetAsync(secondaryObjectThin.Id.Value);
                    secondaryObjectModels.Add(new Models.SecondaryObject()
                    {
                        Id = secondaryObject.Id,
                        Description = secondaryObject.Description,
                        Name = secondaryObject.Name,
                        PrimaryObjectId = primaryObject.Id,
                    });
                }
            }

            var model = new Models.PrimaryObject()
            {
                Id = primaryObject.Id,
                Description = primaryObject.Description,
                Name = primaryObject.Name,
                SecondaryObjects = secondaryObjectModels.OrderBy(_ => _.Name).ToArray(),
            };
            return View(model);
        }

        // POST: PrimaryObjects/Edit/5
        [HttpPost]
        [Route("edit")]
        public async Task<ActionResult> Edit(Guid id, FormCollection collection)
        {
            var model = new Models.PrimaryObject()
            {
                Id = id,
                Description = collection[nameof(Models.PrimaryObject.Description)],
                Name = collection[nameof(Models.PrimaryObject.Name)],
                SecondaryObjects = new Models.SecondaryObject[0],
            };

            try
            {
                await _primaryObjectService.UpdateAsync(id, model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        // GET: PrimaryObjects/Delete/5
        [HttpGet]
        [Route("delete")]
        public async Task<ActionResult> Delete(Guid id)
        {
            var primaryObject = await _primaryObjectService.GetAsync(id);
            var model = new Models.PrimaryObject()
            {
                Id = primaryObject.Id,
                Description = primaryObject.Description,
                Name = primaryObject.Name,
                SecondaryObjects = primaryObject.SecondaryObjects?.Select(so => new Models.SecondaryObject()
                {
                    Id = so.Id,
                    Description = so.Description,
                    Name = so.Name,
                    PrimaryObjectId = primaryObject.Id,
                })?.ToArray() ?? new Models.SecondaryObject[0],
            };
            return View(model);
        }

        // POST: PrimaryObjects/Delete/5
        [HttpPost]
        [Route("delete")]
        public async Task<ActionResult> Delete(Guid id, FormCollection collection)
        {
            try
            {
                await _primaryObjectService.DeleteAsync(id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                var model = new Models.PrimaryObject()
                {
                    Id = id,
                    Description = collection[nameof(Models.PrimaryObject.Description)],
                    Name = collection[nameof(Models.PrimaryObject.Name)],
                    SecondaryObjects = new Models.SecondaryObject[0],
                };

                return View(model);
            }
        }
    }
}

Rightpoint.UnitTesting.Demo.Mvc/Controllers/SecondaryObjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EnsureThat;
using Rightpoint.UnitTesting.Demo.Mvc.Contracts;

namespace Rightpoint.UnitTesting.Demo.Mvc.Controllers
{
    public class SecondaryObjectsController : BaseController
    {
        private readonly ISecondaryObjectService _secondaryObjectService;

        public SecondaryObjectsController(ISecondaryObjectService secondaryObjectService)
        {
            Ensure.That(secondaryObjectService, nameof(secondaryObjectService)).IsNotNull();

            this._secondaryObjectService = secondaryObjectService;
        }

        // GET: SecondaryObjects/Create/5
        [HttpGet]
        [Route("create")]
        public ActionResult Create(Guid id)
        {
            var model = new Models.SecondaryObject()
            {
                PrimaryObjectId = id,
            };
            return View(model);
        }

        // POST: SecondaryObjects/Create/5
        [HttpPost]
        [Route("create")]
        public async Task<ActionResult> Create(Guid id, FormCollection collection)
        {
            var model = new Models.SecondaryObject()
            {
                Description = collection[nameof(Models.SecondaryObject.Description)],
                Name = collection[nameof(Models.SecondaryObject.Name)],
                PrimaryObjectId = id,
            };

            try
            {
                await _secondaryObjectService.CreateAsync(id, model);

                return RedirectToAction("Edit", "PrimaryObjects", new { id = id });
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        // GET: SecondaryObjects/Edit/5
        [HttpGet]
        [Route("edit")]
        public async Task<ActionResult> Edit(Guid id)
        {
            var secondaryObject = await _secondaryObjectService.GetAsync(id);

            var model = new Models.SecondaryObject()
            {
                Id = secondaryObject.Id,
                Description = secondaryObject.Description,
                Name = secondaryObject.Name,
                PrimaryObjectId = secondaryObject.PrimaryObject?.Id,
            };
            return View(model);
        }

        // POST: SecondaryObjects/Edit/5
        [HttpPost]
        [Route("edit")]
        public async Task<ActionResult> Edit(Guid id, FormCollection collection)
        {
            var primaryObjectIdString = collection[nameof(Models.SecondaryObject.PrimaryObjectId)];
            var model = new Models.SecondaryObject()
            {
                Id = id,
                Description = collection[nameof(Models.SecondaryObject.Description)],
                Name = collection[nameof(Models.SecondaryObject.Name)],
                PrimaryObjectId = string.IsNullOrWhiteSpace(primaryObjectIdString) ? null : Guid.Parse(primaryObjectIdString) as Guid?,
            };

            try
            {
                await _secondaryObjectService.UpdateAsync(id, model);

                return RedirectToAction("Edit", "PrimaryObjects", new { id = model.PrimaryObjectId });
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        // GET: SecondaryObjects/Delete/5
        [HttpGet]
        [Route("delete")]
        public async Task<ActionResult> Delete(Guid id)
        {
            var secondaryObject = await _secondaryObjectService.GetAsync(id);
            var model = new Models.SecondaryObject()
            {
                Id = secondaryObject.Id,
                Description = secondaryObject.Description,
                Name = secondaryObject.Name,
                PrimaryObjectId = secondaryObject.PrimaryObject?.Id,
            };
            return View(model);
        }

        // POST: SecondaryObjects/Delete/5
        [HttpPost]
        [Route("delete")]
        public async Task<ActionResult> Delete(Guid id, FormCollection collection)
        {
            Models.SecondaryObject model = null;
            try
            {
                var primaryObjectIdString = collection[nameof(Models.SecondaryObject.PrimaryObjectId)];
                model = new Models.SecondaryObject()
                {
                    Id = id,
                    Description = collection[nameof(Models.SecondaryObject.Description)],
                    Name = collection[nameof(Models.SecondaryObject.Name)],
                    PrimaryObjectId = string.IsNullOrWhiteSpace(primaryObjectIdString) ? null : Guid.Parse(primaryObjectIdString) as Guid?,
                };
                await _secondaryObjectService.DeleteAsync(id);

                return RedirectToAction("Edit", "PrimaryObjects", new { id = model.PrimaryObjectId });
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }
    }
}

Rightpoint.UnitTesting.Demo.Mvc/Views/PrimaryObjects/Create.cshtml
@model Rightpoint.UnitTesting.Demo.Mvc.Models.PrimaryObject

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PrimaryObject</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rightpoint.UnitTesting.Demo.Mvc/Views/PrimaryObjects/Delete.cshtml
@model Rightpoint.UnitTesting.Demo.Mvc.Models.PrimaryObject

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PrimaryObject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Rightpoint.UnitTesting.Demo.Mvc/Views/PrimaryObjects/Edit.cshtml
@model Rightpoint.UnitTesting.Demo.Mvc.Models.PrimaryObject

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PrimaryObject</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondaryObjects, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p>
                    @Html.ActionLink("Create New", "Create", "SecondaryObjects", new { id = Model.Id }, null)
                </p>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.SecondaryObjects.FirstOrDefault().Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SecondaryObjects.FirstOrDefault().Description)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.SecondaryObjects)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", "SecondaryObjects",  new { id = item.Id }, null) |
                                @Html.ActionLink("Delete", "Delete", "SecondaryObjects", new { id = item.Id }, null)
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rightpoint.UnitTesting.Demo.Mvc/Views/PrimaryObjects/Index.cshtml
@model IEnumerable<Rightpoint.UnitTesting.Demo.Mvc.Models.PrimaryObject>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>